# Generated by Django 5.2.5 on 2025-10-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
