# Generated by Django 5.2.5 on 2025-10-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_useractivitylog_user_name_useractivitylog_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('RESTORE', 'Restore'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REAPPROVE', 'Reapprove'), ('SUSPEND', 'Suspend'), ('HOLD', 'Hold'), ('CHANGE_FROM_APPROVED', 'Change From Approved')], max_length=20),
        ),
    ]
