# Generated by Django 5.2.5 on 2025-10-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='case_status',
            field=models.CharField(blank=True, help_text='pending or resolved', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='component',
            field=models.CharField(blank=True, help_text='UI component where action occurred', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='filter_data',
            field=models.JSONField(blank=True, help_text='Stores applied filters as JSON', null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('RESTORE', 'Restore'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REAPPROVE', 'Reapprove'), ('SUSPEND', 'Suspend'), ('HOLD', 'Hold'), ('CHANGE_FROM_APPROVED', 'Change From Approved'), ('SEARCH', 'Search'), ('RESET_FILTERS', 'Reset Filters')], max_length=20),
        ),
    ]
