# Generated by Django 5.1.3 on 2025-03-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='assigned_region',
            field=models.CharField(blank=True, db_index=True, help_text='Region assigned to the volunteer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='dob',
            field=models.DateField(blank=True, db_index=True, help_text='Date of Birth', null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='emergency_contact_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='emergency_contact_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='mode_of_search',
            field=models.CharField(blank=True, choices=[('On Foot', 'On Foot'), ('Vehicle', 'Vehicle'), ('Drone', 'Drone')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='relationship_with_volunteer',
            field=models.CharField(blank=True, db_index=True, help_text='Relationship with the volunteer (e.g., Father, Mother, Spouse)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='search_start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='search_timing',
            field=models.TimeField(blank=True, db_index=True, help_text="Timing for the volunteer's search", null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_group',
            field=models.CharField(blank=True, choices=[('Group A', 'Group A'), ('Group B', 'Group B'), ('Group C', 'Group C')], db_index=True, max_length=50, null=True),
        ),
    ]
