# Generated by Django 5.1.3 on 2025-04-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0004_dummy_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age_range',
            field=models.IntegerField(blank=True, choices=[('0-5', '0 - 5'), ('6-12', '6 - 12'), ('13-17', '13 - 17'), ('18-24', '18 - 24'), ('25-34', '25 - 34'), ('35-44', '35 - 44'), ('45-54', '45 - 54'), ('55-64', '55 - 64'), ('65-74', '65 - 74'), ('75-84', '75 - 84'), ('85-100', '85+')], db_index=True, null=True),
        ),
    ]
