# Generated by Django 5.1.3 on 2025-04-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_alter_person_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='height_range',
            field=models.CharField(blank=True, choices=[('<150', 'Less than 150 cm'), ('150-160', '150 - 160 cm'), ('161-170', '161 - 170 cm'), ('171-180', '171 - 180 cm'), ('181-190', '181 - 190 cm'), ('>190', 'More than 190 cm')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
