# Generated by Django 5.1.3 on 2025-04-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0007_person_height_range_alter_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('personal', 'Personal'), ('office', 'Office'), ('home', 'Home'), ('referral', 'Referral'), ('emergency', 'Emergency'), ('work', 'Work'), ('family', 'Family'), ('friend', 'Friend'), ('medical', 'Medical'), ('school', 'School'), ('legal', 'Legal'), ('other', 'Other')], max_length=10),
        ),
    ]
