# Generated by Django 5.1.3 on 2025-04-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0008_alter_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastknowndetails',
            name='missing_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
