# Generated by Django 5.1.3 on 2025-04-23 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0009_alter_lastknowndetails_missing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='reported_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
