# Generated by Django 5.1.3 on 2025-04-23 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0010_alter_person_reported_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinfo',
            name='id_no',
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='id_type',
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[('aadhar', 'Aadhar'), ('pan', 'PAN'), ('dl', 'Driving License'), ('passport', 'Passport'), ('voterid', 'Voter ID')], max_length=50)),
                ('id_no', models.CharField(max_length=100)),
                ('additional_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='Mainapp.additionalinfo')),
            ],
        ),
    ]
