# Generated by Django 5.1.3 on 2025-04-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0011_remove_additionalinfo_id_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='id_no',
            field=models.CharField(blank=True, help_text='Unique identification number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='id_type',
            field=models.CharField(blank=True, choices=[('aadhar', 'Aadhar'), ('pan', 'PAN'), ('dl', 'Driving License'), ('passport', 'Passport')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='IDCard',
        ),
    ]
