# Generated by Django 5.1.3 on 2025-04-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0012_additionalinfo_id_no_additionalinfo_id_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('brown', 'Brown'), ('green', 'Green'), ('hazel', 'Hazel'), ('red', 'Red'), ('black', 'Black'), ('gray', 'Gray'), ('yellow', 'Yellow'), ('violet', 'Violet')], db_index=True, max_length=50, null=True),
        ),
    ]
