# Generated by Django 5.1.3 on 2025-04-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0013_alter_person_eye_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='fir_photo',
            field=models.FileField(blank=True, null=True, upload_to='fir_photos/'),
        ),
    ]
