# Generated by Django 5.1.3 on 2025-04-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0014_fir_fir_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='case_status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('matched', 'Matched')], db_index=True, default='pending', max_length=10),
        ),
    ]
