# Generated by Django 5.1.3 on 2025-04-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0015_alter_person_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
