# Generated by Django 5.1.3 on 2025-04-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0016_contact_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('Permanent', 'PERMANENT'), ('current', 'CURRENT'), ('old', 'OLD'), ('home', 'HOME'), ('office', 'OFFICE')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo_photo',
            field=models.ImageField(blank=True, null=True, upload_to='All_Photos'),
        ),
    ]
