# Generated by Django 5.1.3 on 2025-04-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0017_alter_address_address_type_alter_person_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Body_Condition',
            field=models.CharField(blank=True, choices=[('decomposed', 'Decomposed'), ('intact', 'Intact'), ('skeletal', 'Skeletal'), ('burnt', 'Burnt'), ('fresh', 'Fresh'), ('normal', 'Normal'), ('unstable', 'Unstable'), ('stable', 'Stable'), ('excess', 'Excess'), ('underweight', 'Underweight'), ('overweight', 'Overweight'), ('obese', 'Obese')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_type',
            field=models.CharField(blank=True, choices=[('permanent', 'PERMANENT'), ('current', 'CURRENT'), ('old', 'OLD'), ('home', 'HOME'), ('office', 'OFFICE')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='condition',
            field=models.CharField(blank=True, choices=[('memory_loss', 'Memory Loss'), ('anxiety', 'Anxiety'), ('shock', 'Shock'), ('depression', 'Depression'), ('fatigue', 'Fatigue'), ('headache', 'Headache'), ('dizziness', 'Dizzy'), ('nausea', 'Nausea'), ('chest_pain', 'Chest Pain')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='hair_type',
            field=models.CharField(blank=True, choices=[('straight', 'STRAIGHT'), ('dashed', 'DASHED'), ('dotted', 'DOTTED'), ('long', 'LONG'), ('broad', 'BROAD'), ('short', 'SHORT'), ('wavy', 'WAVY')], db_index=True, max_length=10, null=True),
        ),
    ]
