# Generated by Django 5.1.3 on 2025-04-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0018_alter_person_body_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='investigation_officer_contacts',
            field=models.CharField(blank=True, null=True),
        ),
    ]
