# Generated by Django 5.1.3 on 2025-04-25 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0019_fir_investigation_officer_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='reported_date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
