# Generated by Django 5.1.3 on 2025-04-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0020_alter_person_reported_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('annulled', 'Annulled'), ('in_relationship', 'In a Relationship'), ('engaged', 'Engaged'), ('domestic_partnership', 'Domestic Partnership'), ('unknown', 'Unknown')], max_length=50),
        ),
    ]
