# Generated by Django 5.1.3 on 2025-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0021_alter_additionalinfo_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
