# Generated by Django 5.1.3 on 2025-04-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0022_alter_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='caste',
            field=models.CharField(blank=True, choices=[('sc', 'Scheduled Caste (SC)'), ('st', 'Scheduled Tribe (ST)'), ('obc', 'Other Backward Class (OBC)'), ('open', 'Open / General'), ('nt', 'Nomadic Tribes (NT)'), ('sbc', 'Special Backward Class (SBC)'), ('vj', 'Vimukta Jati (VJ)'), ('sebc', 'Socially and Educationally Backward Class (SEBC)'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
