# Generated by Django 5.1.3 on 2025-04-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0023_alter_additionalinfo_caste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('permanent', 'PERMANENT'), ('current', 'CURRENT'), ('old', 'OLD'), ('home', 'HOME'), ('office', 'OFFICE')], db_index=True, max_length=50, null=True),
        ),
    ]
