# Generated by Django 5.1.3 on 2025-04-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0024_alter_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_approve_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
