# Generated by Django 5.1.3 on 2025-04-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0025_person_person_approve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(choices=[('gvt', 'Government'), ('private', 'Private')], max_length=10),
        ),
    ]
