# Generated by Django 5.1.3 on 2025-04-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0026_alter_hospital_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='activ_Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Non-Active', 'Non-Active')], default='Active', max_length=10),
        ),
    ]
