# Generated by Django 5.1.3 on 2025-04-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0027_hospital_activ_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='distinctive_mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
