# Generated by Django 5.1.3 on 2025-04-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0028_alter_person_birth_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('permanent', 'PERMANENT'), ('current', 'CURRENT'), ('old', 'OLD'), ('home', 'HOME'), ('office', 'OFFICE'), ('temporary', 'TEMPORARY'), ('billing', 'BILLING'), ('shipping', 'SHIPPING'), ('registered', 'REGISTERED'), ('mailing', 'MAILING'), ('vacation', 'VACATION'), ('rental', 'RENTAL'), ('student', 'STUDENT'), ('family', 'FAMILY'), ('other', 'OTHER')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_type',
            field=models.CharField(blank=True, choices=[('permanent', 'PERMANENT'), ('current', 'CURRENT'), ('old', 'OLD'), ('home', 'HOME'), ('office', 'OFFICE'), ('temporary', 'TEMPORARY'), ('billing', 'BILLING'), ('shipping', 'SHIPPING'), ('registered', 'REGISTERED'), ('mailing', 'MAILING'), ('vacation', 'VACATION'), ('rental', 'RENTAL'), ('student', 'STUDENT'), ('family', 'FAMILY'), ('other', 'OTHER')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='phone_no',
            field=models.CharField(blank=True, help_text='Contact number of the police station', max_length=50, null=True),
        ),
    ]
