# Generated by Django 5.1.3 on 2025-05-02 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0029_alter_address_address_type_alter_contact_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_persons', to=settings.AUTH_USER_MODEL),
        ),
    ]
