# Generated by Django 5.1.3 on 2025-05-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0030_person_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('hold', 'Hold'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
