# Generated by Django 5.1.3 on 2025-05-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0031_user_registered_at_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
