# Generated by Django 5.1.3 on 2025-05-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0033_user_status_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_by_google',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
