# Generated by Django 5.1.3 on 2025-05-03 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0035_alter_user_password_alter_user_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='reported_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
