# Generated by Django 5.1.3 on 2025-05-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0036_alter_person_reported_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('version', models.CharField(max_length=100)),
                ('added', models.TextField(blank=True, null=True)),
                ('modified', models.TextField(blank=True, null=True)),
                ('tested', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
