# Generated by Django 5.1.3 on 2025-05-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0037_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='added',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='modified',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='tested',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='version',
            field=models.CharField(max_length=50),
        ),
    ]
