# Generated by Django 5.1.3 on 2025-05-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0038_alter_changelog_added_alter_changelog_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
