# Generated by Django 5.1.3 on 2025-05-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0039_changelog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status_reason',
            field=models.TextField(blank=True, help_text='Reason for suspension or hold', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_approve_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('on_hold', 'On Hold'), ('archived', 'Archived')], default='pending', max_length=10),
        ),
    ]
