# Generated by Django 5.1.3 on 2025-05-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0040_person_status_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(choices=[('gvt', 'Government'), ('semi_gvt', 'Semi-Government'), ('private', 'Private')], max_length=10),
        ),
    ]
