# Generated by Django 5.1.3 on 2025-05-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0042_alter_hospital_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bodies_conditon',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
