# Generated by Django 5.1.3 on 2025-05-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0043_person_bodies_conditon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='bodies_conditon',
            new_name='bodies_condition',
        ),
        migrations.AddField(
            model_name='person',
            name='up_condition',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
