# Generated by Django 5.1.3 on 2025-05-08 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0044_rename_bodies_conditon_person_bodies_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_type', models.CharField(choices=[('matched', 'Matched'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_matches', to='Mainapp.person')),
                ('unidentified_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_matches', to='Mainapp.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
