# Generated by Django 5.1.3 on 2025-05-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0045_personmatchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmatchhistory',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
