# Generated by Django 5.1.3 on 2025-05-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0046_personmatchhistory_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmatchhistory',
            name='match_parameters',
            field=models.JSONField(default=dict, help_text='Detailed matching parameters'),
        ),
        migrations.AlterField(
            model_name='personmatchhistory',
            name='match_type',
            field=models.CharField(choices=[('potential', 'Potential Match'), ('matched', 'Matched'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed')], max_length=20),
        ),
    ]
