# Generated by Django 5.1.3 on 2025-05-09 05:14

import Mainapp.models.person_match_history
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0047_personmatchhistory_match_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmatchhistory',
            name='match_id',
            field=models.CharField(blank=True, default=Mainapp.models.person_match_history.generate_custom_match_id, editable=False, max_length=30, null=True),
        ),
    ]
