# Generated by Django 5.1.3 on 2025-05-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0049_alter_personmatchhistory_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmatchhistory',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
