# Generated by Django 5.1.3 on 2025-05-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0050_personmatchhistory_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmatchhistory',
            name='unreject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
