# Generated by Django 5.1.3 on 2025-05-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0051_personmatchhistory_unreject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmatchhistory',
            name='confirmation_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
