# Generated by Django 5.1.3 on 2025-05-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0052_personmatchhistory_confirmation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmatchhistory',
            name='unconfirm_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
