# Generated by Django 5.1.3 on 2025-05-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0053_personmatchhistory_unconfirm_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='matched_person_id',
            field=models.UUIDField(blank=True, help_text='UUID of the matched person', null=True),
        ),
    ]
