# Generated by Django 5.1.3 on 2025-05-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0054_person_matched_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
