# Generated by Django 5.1.3 on 2025-05-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0055_user_profile_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='id_type',
            field=models.CharField(blank=True, choices=[('aadhar', 'Aadhar'), ('pan', 'PAN'), ('dl', 'Driving License'), ('passport', 'Passport'), ('voterID', 'VoterID')], max_length=100, null=True),
        ),
    ]
