# Generated by Django 5.1.3 on 2025-05-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0056_alter_additionalinfo_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='case_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
