# Generated by Django 5.1.3 on 2025-05-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0057_person_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='case_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
    ]
