# Generated by Django 5.1.3 on 2025-05-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0058_alter_person_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='id_type',
            field=models.CharField(blank=True, choices=[('aadhar_card', 'Aadhar Card'), ('pan_card', 'PAN Card'), ('driving_license', 'Driving License'), ('passport', 'Passport'), ('voter_id_card', 'Voter ID Card')], max_length=100, null=True),
        ),
    ]
