# Generated by Django 5.1.3 on 2025-05-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0059_alter_additionalinfo_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='death_type',
            field=models.CharField(blank=True, choices=[('natural', 'Natural Causes'), ('accident', 'Accident'), ('homicide', 'Homicide'), ('suicide', 'Suicide'), ('unknown', 'Unknown'), ('other', 'Other'), ('disease', 'Disease'), ('poisoning', 'Poisoning'), ('drowning', 'Drowning'), ('burn', 'Burn'), ('starvation', 'Starvation'), ('hypothermia', 'Hypothermia'), ('heatstroke', 'Heatstroke'), ('medical_error', 'Medical Error'), ('war', 'War'), ('execution', 'Execution'), ('complication', 'Complication'), ('drug_overdose', 'Drug Overdose'), ('asphyxiation', 'Asphyxiation')], default='unknown', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='mother_tongue',
            field=models.CharField(blank=True, choices=[('hindi', 'Hindi'), ('english', 'English'), ('bengali', 'Bengali'), ('marathi', 'Marathi'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('malayalam', 'Malayalam'), ('kannada', 'Kannada'), ('punjabi', 'Punjabi'), ('gujarati', 'Gujarati'), ('urdu', 'Urdu'), ('oriya', 'Oriya'), ('assamese', 'Assamese'), ('sindhi', 'Sindhi'), ('nepali', 'Nepali'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='religion',
            field=models.CharField(blank=True, choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('sikh', 'Sikh'), ('christian', 'Christian'), ('buddhist', 'Buddhist'), ('jain', 'Jain'), ('zoroastrian', 'Zoroastrian'), ('jewish', 'Jewish'), ('atheist', 'Atheist'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
