# Generated by Django 5.1.3 on 2025-05-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0060_person_death_type_alter_additionalinfo_mother_tongue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('reporting_person', 'Reporting'), ('volunteer', 'Volunteer'), ('family', 'Family'), ('admin', 'Admin'), ('police_station', 'Police Station'), ('medical_staff', 'Medical Staff')], default='reporting_person', max_length=20),
        ),
    ]
