# Generated by Django 5.1.3 on 2025-05-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0061_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_type',
            field=models.CharField(blank=True, choices=[('missing_address', 'MISSING ADDRESS'), ('body_found', 'BODY FOUND'), ('last_found', 'LAST FOUND'), ('permanent', 'PERMANENT'), ('current', 'CURRENT'), ('old', 'OLD'), ('home', 'HOME'), ('office', 'OFFICE'), ('temporary', 'TEMPORARY'), ('billing', 'BILLING'), ('shipping', 'SHIPPING'), ('registered', 'REGISTERED'), ('mailing', 'MAILING'), ('vacation', 'VACATION'), ('rental', 'RENTAL'), ('student', 'STUDENT'), ('family', 'FAMILY'), ('other', 'OTHER')], db_index=True, max_length=50, null=True),
        ),
    ]
