# Generated by Django 5.1.3 on 2025-05-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0063_caste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='caste',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
