# Generated by Django 5.1.3 on 2025-05-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0064_alter_additionalinfo_caste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(choices=[('govt', 'Government'), ('semi_govt', 'Semi-Government'), ('private', 'Private')], max_length=10),
        ),
    ]
