# Generated by Django 5.1.3 on 2025-05-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0065_alter_hospital_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='educational_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='occupation_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='caste',
            field=models.CharField(blank=True, choices=[('sc', 'Scheduled Caste (SC)'), ('st', 'Scheduled Tribe (ST)'), ('obc', 'Other Backward Class (OBC)'), ('open', 'Open / General'), ('nt', 'Nomadic Tribes (NT)'), ('sbc', 'Special Backward Class (SBC)'), ('vj', 'Vimukta Jati (VJ)'), ('sebc', 'Socially and Educationally Backward Class (SEBC)'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='education_details',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='occupation_details',
            field=models.CharField(blank=True, max_length=1550, null=True),
        ),
    ]
