# Generated by Django 5.1.3 on 2025-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0067_person_category_person_chronic_illness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmatchhistory',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
