# Generated by Django 5.1.3 on 2025-06-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0068_personmatchhistory_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='activ_Status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Non-Active', 'Non-Active')], default='Active', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(blank=True, choices=[('govt', 'Government'), ('semi_govt', 'Semi-Government'), ('private', 'Private')], max_length=10, null=True),
        ),
    ]
