# Generated by Django 5.1.3 on 2025-06-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0070_alter_policestation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policestation',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the police station', max_length=150, null=True),
        ),
    ]
