# Generated by Django 5.1.3 on 2025-06-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0071_alter_policestation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
