# Generated by Django 5.1.3 on 2025-06-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0072_person_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='subcaste',
            field=models.CharField(blank=True, choices=[('mahar', 'Mahar'), ('chambhar', 'Chambhar'), ('brahmin', 'Brahmin'), ('gurdian', 'Gurdian'), ('maratha', 'Maratha'), ('rajput', 'Rajput'), ('jain', 'Jain'), ('teli', 'Teli'), ('kumbhar', 'Kumbhar')], max_length=50, null=True),
        ),
    ]
