# Generated by Django 5.1.3 on 2025-06-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0073_alter_additionalinfo_subcaste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='disappearance_type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='specific_reason',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
