# Generated by Django 5.1.3 on 2025-06-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0074_alter_person_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='tested',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
