# Generated by Django 5.1.3 on 2025-06-26 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0075_alter_changelog_tested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, choices=[('fir_scan', 'FIR Scan'), ('cctv', 'CCTV Footage'), ('witness_statement', 'Witness Statement'), ('last_known_photo', 'Last Known Photo'), ('scene_photo', 'Scene Photo'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='fir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Mainapp.fir'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_known_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Mainapp.lastknowndetails'),
        ),
        migrations.AddField(
            model_name='document',
            name='person_type',
            field=models.CharField(blank=True, choices=[('missing person', 'Missing Person'), ('unidentified person', 'Unidentified Person'), ('unidentified body', 'Unidentified Body')], max_length=20, null=True),
        ),
    ]
