# Generated by Django 5.1.3 on 2025-06-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0076_remove_document_type_remove_fir_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, choices=[('fir_scan', 'FIR Scan'), ('fir_attachment', 'FIR Attachment'), ('incident_report', 'Incident Report'), ('cctv', 'CCTV Footage'), ('scene_photo', 'Scene Photo'), ('witness_statement', 'Witness Statement'), ('last_known_photo', 'Last Known Photo'), ('last_known_location_note', 'Last Known Location Note'), ('last_known_description', 'Last Known Description'), ('belonging_bag', 'Belonging - Bag'), ('belonging_watch', 'Belonging - Watch'), ('belonging_pocket', 'Belonging - Pocket Items'), ('belonging_wallet', 'Belonging - Wallet'), ('belonging_mobile', 'Belonging - Mobile Phone'), ('belonging_clothing', 'Belonging - Clothing'), ('other', 'Other')], max_length=90, null=True),
        ),
    ]
