# Generated by Django 5.1.3 on 2025-06-27 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0077_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'rtf', 'mp3', 'wav', 'ogg', 'mp4', 'mov', 'avi', 'mkv', 'zip', 'rar'])]),
        ),
    ]
