# Generated by Django 5.1.3 on 2025-07-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0079_document_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='death_type',
            field=models.CharField(blank=True, choices=[('natural', 'Natural Causes'), ('accident', 'Accident'), ('homicide', 'Homicide'), ('suicide', 'Suicide'), ('unknown', 'Unknown'), ('other', 'Other'), ('disease', 'Disease'), ('poisoning', 'Poisoning'), ('drowning', 'Drowning'), ('burn', 'Burn'), ('starvation', 'Starvation'), ('hypothermia', 'Hypothermia'), ('heatstroke', 'Heatstroke'), ('medical_error', 'Medical Error'), ('war', 'War'), ('execution', 'Execution'), ('complication', 'Complication'), ('drug_overdose', 'Drug Overdose'), ('asphyxiation', 'Asphyxiation')], max_length=20, null=True),
        ),
    ]
