# Generated by Django 5.1.3 on 2025-07-21 06:38

import Mainapp.models.match_missing_with_unidentified_body
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0080_alter_person_death_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missing_match_with_body',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_id', models.CharField(blank=True, default=Mainapp.models.match_missing_with_unidentified_body.generate_custom_match_id, editable=False, max_length=30, null=True, unique=True)),
                ('match_type', models.CharField(choices=[('potential', 'Potential Match'), ('matched', 'Matched'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed')], max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('match_parameters', models.JSONField(default=dict, help_text='Detailed matching parameters')),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('unreject_reason', models.TextField(blank=True, null=True)),
                ('confirmation_note', models.TextField(blank=True, null=True)),
                ('unconfirm_reason', models.TextField(blank=True, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_matches', to='Mainapp.person')),
                ('unidentified_bodies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ub_matches', to='Mainapp.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
