# Generated by Django 5.1.3 on 2025-07-22 11:03

import django.db.models.deletion
from django.db import migrations, models
def clean_invalid_json_fields(apps, schema_editor):
    Person = apps.get_model("Mainapp", "Person")
    db_alias = schema_editor.connection.alias

    json_fields = [
        "dental_condition",
        "healed_fractures",
        "lung_bone_pathology",
        "medical_anomalies",
        "prosthetics_amputation",
        "substance_use",
        "surgery_implants",
        "chronic_illness_latest",  # in case the field was added in earlier attempts
    ]

    for person in Person.objects.using(db_alias).all():
        modified = False
        for field in json_fields:
            value = getattr(person, field, None)
            if value and isinstance(value, str) and not value.startswith("[") and not value.startswith("{"):
                setattr(person, field, [value])
                modified = True
        if modified:
            person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0081_missing_match_with_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing_match_with_body',
            name='missing_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_body_matches', to='Mainapp.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dental_condition',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='healed_fractures',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lung_bone_pathology',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='medical_anomalies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='prosthetics_amputation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='substance_use',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='surgery_implants',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
