# Generated by Django 5.1.3 on 2025-07-21 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0081_missing_match_with_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='chronic_illness_new',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='missing_match_with_body',
            name='missing_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_body_matches', to='Mainapp.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dental_condition',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='healed_fractures',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lung_bone_pathology',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='medical_anomalies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='prosthetics_amputation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='substance_use',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='surgery_implants',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
