# Generated by Django 5.1.3 on 2025-07-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0082_remove_person_chronic_illness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='add_chronic_illness',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
