# Generated by Django 5.1.3 on 2025-07-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0082_person_chronic_illnesss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='chronic_illnesss',
            new_name='chronic_illness_new',
        ),
    ]
