# Generated by Django 5.1.3 on 2025-07-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0082_person_chronic_illness_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='chronic_illness_new',
        ),
    ]
