# Generated by Django 5.1.3 on 2025-07-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0082_alter_missing_match_with_body_missing_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='chronic_illness_latest',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
