# Generated by Django 5.1.3 on 2025-07-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0083_person_chronic_illness_latest'),
    ]

    operations = [
    ]
