# Generated by Django 5.1.3 on 2025-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0083_person_add_chronic_illness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dna_match',
            field=models.CharField(blank=True, choices=[('match_found', 'Match Found'), ('no_match', 'No Match'), ('not_available', 'Not Available'), ('pending', 'Pending')], max_length=20, null=True),
        ),
    ]
