# Generated by Django 5.1.3 on 2025-07-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0083_remove_person_chronic_illness_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='chronic_illness_new',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
