# Generated by Django 5.1.3 on 2025-07-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0084_alter_person_dna_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastknowndetails',
            name='last_seen_location',
            field=models.TextField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lastknowndetails',
            name='missing_location_details',
            field=models.TextField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_mark',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='distinctive_mark',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
