# Generated by Django 5.1.3 on 2025-08-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0085_alter_lastknowndetails_last_seen_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
