# Generated by Django 5.1.3 on 2025-07-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0085_remove_person_chronic_illness_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='add_chronic_illness',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
