# Generated by Django 5.2.5 on 2025-08-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0086_user_last_login_ip_user_last_login_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='matched_case_id',
            field=models.CharField(blank=True, help_text='Case ID of the matched person or entity', max_length=50, null=True),
        ),
    ]
