# Generated by Django 5.1.3 on 2025-08-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0087_person_matched_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='confirmed_from',
            field=models.CharField(blank=True, choices=[('MP', 'Missing Person'), ('UP', 'Unidentified Person'), ('UB', 'Unidentified Body')], help_text='Indicates whether the confirmation was initiated from Missing Person, Unidentified Person, or Unidentified Body section', max_length=20, null=True),
        ),
    ]
