# Generated by Django 5.1.3 on 2025-08-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0088_person_confirmed_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='confirmed_from',
            field=models.CharField(blank=True, choices=[('MPtoUP', 'Missing Person → Unidentified Person'), ('MPtoUB', 'Missing Person → Unidentified Body'), ('UPtoMP', 'Unidentified Person → Missing Person'), ('UBtoMP', 'Unidentified Body → Missing Person')], help_text='Indicates whether the confirmation was initiated from Missing Person, Unidentified Person, or Unidentified Body section', max_length=20, null=True),
        ),
    ]
