# Generated by Django 5.1.3 on 2025-10-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0089_alter_person_confirmed_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('reporting_person', 'Reporting'), ('volunteer', 'Volunteer'), ('family', 'Family'), ('admin', 'Admin'), ('police_station', 'Police Station'), ('medical_staff', 'Medical Staff'), ('anonymous', 'ANONYMOUS')], default='reporting_person', max_length=20),
        ),
    ]
